services:
  nav-sim:
    build: .
    image: nav-sim:jazzy
    container_name: nav_sim_env
    security_opt:
      - seccomp:unconfined
    shm_size: '512m'
    ports:
      - "6080:80" # Open localhost:6080 in your browser once its running
    volumes:
      - ./ros2_ws:/home/ubuntu/ros2_ws
    restart: unless-stopped
  nav-sim-gpu:
    profiles: ["gpu"]
    build: .
    image: nav-sim:jazzy
    container_name: nav_sim_env_gpu
    security_opt:
      - seccomp:unconfined
    shm_size: '512m'
    ports:
      - "6080:80"
    volumes:
      - ./ros2_ws/src:/home/ubuntu/ros2_ws/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped